### ISSUE TITLE
Getting meteorpp::ejdb_exception

### ISSUE THREAD

**Issue by esromneb** [almightycouch/meteorpp#1]
I was able to compile this project into my app (a weird way admittedly).  I know everything is connected because I am able to crash my c++ app from meteor.  Using the example from the readme I get:

```bash
terminate called after throwing an instance of 'meteorpp::ejdb_exception'
  what():  invalid bson _id field

```

Do I need to update something?

**Comment by redrabbit** [comment]
Hi @esromneb, currently away from home without laptop but I think the exception you get is due to the use of Meteor using random string for IDs by default.

You must configure your collection(s) as follow in order to use `Mongo.ObjectID`.

```javascript
Posts = new Mongo.Collection("posts", {idGeneration: 'MONGO'});
```

See the [`Mongo.Collection`](https://docs.meteor.com/api/collections.html#Mongo-Collection) documentation for further informations.

Also I wrote a [blog post](https://almightycouch.com/blog/meteor-ddp-minimongo-implementation-cpp) about Meteor++ a while ago, you might also want to check it out.

**Comment by redrabbit** [comment]
Closing this. If the problem persists please re-open the issue.
